/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SendRouteImport } from './routes/send'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as LockRouteImport } from './routes/lock'
import { Route as HomeRouteImport } from './routes/home'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as DailyBriefRouteImport } from './routes/daily-brief'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountAccountIdRouteImport } from './routes/account.$accountId'

const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyBriefRoute = DailyBriefRouteImport.update({
  id: '/daily-brief',
  path: '/daily-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountIdRoute = AccountAccountIdRouteImport.update({
  id: '/account/$accountId',
  path: '/account/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/assistant': typeof AssistantRoute
  '/contacts': typeof ContactsRoute
  '/daily-brief': typeof DailyBriefRoute
  '/developer': typeof DeveloperRoute
  '/home': typeof HomeRoute
  '/lock': typeof LockRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/account/$accountId': typeof AccountAccountIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/assistant': typeof AssistantRoute
  '/contacts': typeof ContactsRoute
  '/daily-brief': typeof DailyBriefRoute
  '/developer': typeof DeveloperRoute
  '/home': typeof HomeRoute
  '/lock': typeof LockRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/account/$accountId': typeof AccountAccountIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/assistant': typeof AssistantRoute
  '/contacts': typeof ContactsRoute
  '/daily-brief': typeof DailyBriefRoute
  '/developer': typeof DeveloperRoute
  '/home': typeof HomeRoute
  '/lock': typeof LockRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/account/$accountId': typeof AccountAccountIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/assistant'
    | '/contacts'
    | '/daily-brief'
    | '/developer'
    | '/home'
    | '/lock'
    | '/receive'
    | '/send'
    | '/settings'
    | '/store'
    | '/account/$accountId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/assistant'
    | '/contacts'
    | '/daily-brief'
    | '/developer'
    | '/home'
    | '/lock'
    | '/receive'
    | '/send'
    | '/settings'
    | '/store'
    | '/account/$accountId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/assistant'
    | '/contacts'
    | '/daily-brief'
    | '/developer'
    | '/home'
    | '/lock'
    | '/receive'
    | '/send'
    | '/settings'
    | '/store'
    | '/account/$accountId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AssistantRoute: typeof AssistantRoute
  ContactsRoute: typeof ContactsRoute
  DailyBriefRoute: typeof DailyBriefRoute
  DeveloperRoute: typeof DeveloperRoute
  HomeRoute: typeof HomeRoute
  LockRoute: typeof LockRoute
  ReceiveRoute: typeof ReceiveRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  StoreRoute: typeof StoreRoute
  AccountAccountIdRoute: typeof AccountAccountIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-brief': {
      id: '/daily-brief'
      path: '/daily-brief'
      fullPath: '/daily-brief'
      preLoaderRoute: typeof DailyBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountId': {
      id: '/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/account/$accountId'
      preLoaderRoute: typeof AccountAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AssistantRoute: AssistantRoute,
  ContactsRoute: ContactsRoute,
  DailyBriefRoute: DailyBriefRoute,
  DeveloperRoute: DeveloperRoute,
  HomeRoute: HomeRoute,
  LockRoute: LockRoute,
  ReceiveRoute: ReceiveRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  StoreRoute: StoreRoute,
  AccountAccountIdRoute: AccountAccountIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
