import type { BrowserDappDefinition } from "./types";

/** Curated Sui ecosystem dapps for the in-app browser home screen. */
export const SUI_DAPPS: BrowserDappDefinition[] = [
  {
    id: "flowx",
    name: "FlowX",
    description: "DEX aggregator and liquidity on Sui",
    url: "https://flowx.finance",
    category: "trading",
    iconUrl: "https://flowx.finance/favicon.ico",
    verified: true,
  },
  {
    id: "cetus",
    name: "Cetus",
    description: "Concentrated liquidity and swaps",
    url: "https://www.cetus.zone",
    category: "trading",
    iconUrl: "https://www.cetus.zone/favicon.ico",
    verified: true,
  },
  {
    id: "aftermath",
    name: "Aftermath",
    description: "Smart order router and DeFi suite",
    url: "https://aftermath.finance",
    category: "defi",
    iconUrl: "https://aftermath.finance/favicon.ico",
    verified: true,
  },
  {
    id: "bluefin",
    name: "Bluefin",
    description: "Perpetuals and pro trading",
    url: "https://trade.bluefin.io",
    category: "trading",
    iconUrl: "https://trade.bluefin.io/favicon.ico",
    verified: true,
  },
  {
    id: "turbos",
    name: "Turbos",
    description: "CLMM DEX on Sui",
    url: "https://app.turbos.finance",
    category: "trading",
    iconUrl: "https://app.turbos.finance/favicon.ico",
    verified: true,
  },
  {
    id: "navi",
    name: "Navi",
    description: "Lending and borrowing protocol",
    url: "https://app.naviprotocol.io",
    category: "yield",
    iconUrl: "https://app.naviprotocol.io/favicon.ico",
    verified: true,
  },
  {
    id: "scallop",
    name: "Scallop",
    description: "Money market and lending",
    url: "https://app.scallop.io",
    category: "yield",
    iconUrl: "https://app.scallop.io/favicon.ico",
    verified: true,
  },
  {
    id: "tradeport",
    name: "TradePort",
    description: "NFT marketplace aggregator",
    url: "https://www.tradeport.xyz",
    category: "nfts",
    iconUrl: "https://www.tradeport.xyz/favicon.ico",
    verified: true,
  },
  {
    id: "clutchy",
    name: "Clutchy",
    description: "NFT launchpad and marketplace",
    url: "https://clutchy.io",
    category: "nfts",
    iconUrl: "https://clutchy.io/favicon.ico",
  },
  {
    id: "suivision",
    name: "Suivision",
    description: "Explorer and analytics",
    url: "https://suivision.xyz",
    category: "infrastructure",
    iconUrl: "https://suivision.xyz/favicon.ico",
    verified: true,
  },
  {
    id: "suiscan",
    name: "SuiScan",
    description: "Block explorer for Sui",
    url: "https://suiscan.xyz",
    category: "infrastructure",
    iconUrl: "https://suiscan.xyz/favicon.ico",
    verified: true,
  },
];
